module Rugular
  class Abstract < Thor::Group
    include Thor::Actions

    argument :folder, desc: 'Component folder you want to abstract'
    desc <<-DESC
      The abstract command copies the contents of any folder nested one-level
      beneath ``src/components`` into the ``~/bower_components`` folder where
      it is treated like a bower component.

      The command will ask some setup questions to generate a bower.json. It is
      recommended that the bower component folders generated by rugular are NOT
      edited by hand. Instead, the only updates should occur by repeated use of
      the ``rugular abstract`` command.
    DESC

    def check_for_rugular_directory
      ::Rugular::AppChecker.check_for_rugular_directory(
        task_name: self.class.name,
        root_directory: destination_root
      )
    end

    def check_for_folder
      fail unless File.directory? "src/components/#{folder}"
    end

    def ask_for_questions
      yes = ask('what is your favorite flavor of ice cream')
    end

    def copy_bower_file
      puts yes
      puts git_username
    end

    def file_copy_folder_into_bower_src_folder
    end

    def add_bower_src_folder_contents_to_main_key_in_bower_json
    end

    private

    def bower_json_hash

    end

    def git_username
      "#{`git config user.name`} <#{`git config user.email`}>"
    end
  end
end
