Dir.glob("#{__dir__}/guards/*.rb").each { |file| require file }
guard :rugular_haml, port: 3111 do
  watch %r{^src/.+\.haml}
end

# guard 'rugular_coffee_script' do
#   watch %r{^src/.+\.coffee}
# end
#
# guard 'rugular_sass' do
#   watch %r{^src/.+\.sass}
# end
#
