web: http-server .tmp
guard: bundle exec guard --guardfile=$(bundle show rugular)/lib/rugular/tasks/server/Guardfile
sass: sass --watch --load-path src src/application.sass:dist/application.css
karma: ./node_modules/karma/bin/karma start karma.conf

